### ISSUE TITLE
Add probot/owners app to this repo

### ISSUE THREAD

**Issue by patcon** [ournetworks/ournetworks.ca#13]
Here are some statements -- :mag: facts, :heart: feelings, and :bulb: ideas -- around this issue:

1. :mag: @dcwalk and @garrying committed most of content.
1. :mag: Getting reviews is part of our internal process.
1. :mag: GitHub auto-suggests reviewers based on `git-blame` data.
1. :heart: I feel that default GitHub behavior currently encourages the people who've already done work, to do more work.
1. :mag: Even when accountability is agreed, to "watch" a repo is done at a personal account level -- GitHub orgs can't change others' watch settings.
1. :mag:[ `OWNERS` spec](https://help.github.com/articles/about-codeowners/) is a way to indicate with intention who is responsible for areas of repo.
1. :mag: `OWNERS` is [supported by GitHub protected branch settings](https://help.github.com/articles/about-protected-branches/).
1. :mag: `OWNERS` has [a probot plugin](https://github.com/bkeepers/probot-owners) for automatically mentioning owners into pull-requests.
1. :bulb: Let's add an `OWNERS` file to this repo and others that we all look after, with all of us responsible for full repo: @patcon, @garrying @dcwalk @benhylau 
1. :bulb: Let's enable `probot-owners` plugin on the whole GitHub org.
1. :bulb: Let's consider doing this in other repos going forward.

Yes? No? Is this asking too much attention of everyone? Or is it helping us all stay accountable to one another? :heart: :)

**Comment by dcwalk** [comment]
@patcon -- I think it might just be a long day and I'm behind, but I'm not 100% clear what you are asking, this is how I interpret the ask:

Enable probot/configurator on this organization & repo, add an OWNERS file, and ?? (then I get lost, sorry!) I think we decided earlier that @garrying and I would focus more on the website than others, with @garrying taking the lead, over responsibilizing us all. TBH I'm not sure which is better in this case, as it is prep for a specific event (with DEADLINES) I think we need a more focused group moving faster than we usually would.

**Comment by patcon** [comment]
Yes, sorry, long days :) I just saw that GitHub always suggests that original writers review PRs -- usually you. Thought maybe it should be all of us, but regardless, the suggestion was meant to codify whatever we wanted -- an `OWNERS` file saying who gets plugged into PRs automatically by a bot.

I missed that detail about @garrying doing website, but if we were using this tactic before, he would get cc'd into each PR by the bot :)

**Comment by dcwalk** [comment]
Ah, thanks for clarifying! I'm not against using OWNERS to codify this, but I guess I'm also not feeling a strong need to implement either

**Comment by patcon** [comment]
Totally. Guess I'm often distracted by goal of sharing with other community projects :) (I was working on a [`cookiecutter`](https://github.com/audreyr/cookiecutter#readme) template earlier that day.)

I'll save it for another time 🎉
