### ISSUE TITLE
Yama-ichi inspiration

### ISSUE THREAD

**Issue by patcon** [ournetworks/ournetworks.ca#21]
A place to bank inspirations for the yama ichi page, assuming this doesn't exist anywhere else :)

cc: @dcwalk

**Comment by dcwalk** [comment]
logo

![internet-black-market-logo](https://user-images.githubusercontent.com/4692834/39683607-787481e0-5184-11e8-809c-35255ac1fbdb.png)

**Comment by dcwalk** [comment]
ambient gifs

![tumblr_os7ky1cgfj1vxnjybo1_540](https://user-images.githubusercontent.com/4692834/39683627-98475bd2-5184-11e8-8512-4c99c5a4fee5.gif)

![tumblr_otm0soc5ew1vxnjybo1_500](https://user-images.githubusercontent.com/4692834/39683644-a706f9f2-5184-11e8-942a-705cb69f25a0.gif)

![tumblr_ox9eb2vv7d1vxnjybo1_540](https://user-images.githubusercontent.com/4692834/39683647-ade4ea5e-5184-11e8-967c-646a5f494b14.gif)

**Comment by dcwalk** [comment]
Early virality, proto-memes 
![dcs4gltv0aawijq](https://user-images.githubusercontent.com/4692834/39683693-f418e91c-5184-11e8-931e-adbee722825c.jpg)

<img width="1280" alt="screen shot 2018-05-06 at 11 27 35 pm" src="https://user-images.githubusercontent.com/4692834/39683746-2fb912bc-5185-11e8-838d-9c4c9e561215.png">


![Uploading Screen Shot 2018-05-06 at 11.28.04 PM.png…]()

**Comment by dcwalk** [comment]
Oh, just relalized this is in ournetworks.ca, not sure if it should be in 2018 instead.

**Comment by dcwalk** [comment]
closing! we did a thing :))
